name: NASA PROJECT CI
  on:
    push:
      branches: [master]
    pull_request:
      branches: [master]  
jobs:
  runs-on: ubuntu-latest
  steps:
    -name: checkout to git repo
     uses: actions/checkout@v3.0.0
    -name: Setup Node.js environment
     uses: actions/setup-node@v3.0.0
     with:
      node-version: 14.x
    -run: npm install
    -run: npm client
    -run: npm run build --prefix client 
    -run: npm test   